### ISSUE TITLE
"poll_text_duration" in config does not work.

### ISSUE THREAD

**Issue by Oyplap** [TeamEXAngus/Polls-EXILED2#1]
"poll_text_duration" in config does not work. When I do: "poll_text_duration: 30" in the config, it does not work. It only shows the message for 5 seconds.

**Comment by TeamEXAngus** [comment]
I've tracked down the bug and will release and update tonight

**Comment by Oyplap** [comment]
Thanks!

**Comment by Oyplap** [comment]
Still does not work with the latest release :(

**Comment by TeamEXAngus** [comment]
> Still does not work with the latest release :(

Okay, fixed for real this time

**Comment by Oyplap** [comment]
Works! Thank you 👍
